export * from './home/home.component';
export * from './loans-view/loans-view.component';
export * from './login/login.component';
export * from './signup/signup.component';
export * from './profile/profile.component';
export * from './edit-profile/edit-profile.component';
export * from './reset-password/reset-password.component';
export * from './wallet/wallet.component';
export * from './get-loan/getloan.component'